---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: unfuckify
  name: unfuckify
  entry: ghcr.io/nunokaeru/unfuckify:latest unfuckify
  description: Unfucks C++ repositories by removing 'auto'
  types_or: [c++]
  language: docker_image

- id: unfuckify-dev
  name: unfuckify-dev
  entry: nunokaeru/unfuckify:dev unfuckify
  description: Unfucks C++ repositories by removing 'auto'
  types_or: [c++]
  language: docker_image
