name: Release
on:
  push:
    tags:
      - "v*"

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Update apt and install dependencies
        run: |
          sudo apt update
          sudo apt install cmake ninja-build gcc g++ \
            clang-20 llvm-20 libclang-20-dev clang-tools-20 \
            libedit-dev zlib1g-dev libzstd-dev libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake --preset linux-clang

      - name: Build
        run: cmake --build --preset linux-clang

      - name: Run tests
        run: ctest --preset linux-clang

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
